services:
  payment-processor-service:
    build: ./
    container_name: payment-processor-service
    restart: always
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
